# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        source ~/.cargo/env
        rustup target add x86_64-unknown-linux-musl
        python -m pip install --upgrade pip
        pip install setuptools-rust setuptools wheel maturin
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip list
    - name: Build wheels 
      run: |
        python setup.py bdist_wheel
